// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/vessel/vessel.proto

package go_micro_srv_vessel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Vessel struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9817d4490e61c20d, []int{0}
}
func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (dst *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(dst, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type Specification struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=max_weight,json=maxWeight" json:"max_weight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Specification) Reset()         { *m = Specification{} }
func (m *Specification) String() string { return proto.CompactTextString(m) }
func (*Specification) ProtoMessage()    {}
func (*Specification) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9817d4490e61c20d, []int{1}
}
func (m *Specification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Specification.Unmarshal(m, b)
}
func (m *Specification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Specification.Marshal(b, m, deterministic)
}
func (dst *Specification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Specification.Merge(dst, src)
}
func (m *Specification) XXX_Size() int {
	return xxx_messageInfo_Specification.Size(m)
}
func (m *Specification) XXX_DiscardUnknown() {
	xxx_messageInfo_Specification.DiscardUnknown(m)
}

var xxx_messageInfo_Specification proto.InternalMessageInfo

func (m *Specification) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Specification) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type Response struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels" json:"vessels,omitempty"`
	Created              bool      `protobuf:"varint,3,opt,name=created" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_vessel_9817d4490e61c20d, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *Response) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.micro.srv.vessel.Vessel")
	proto.RegisterType((*Specification)(nil), "go.micro.srv.vessel.Specification")
	proto.RegisterType((*Response)(nil), "go.micro.srv.vessel.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for VesselService service

type VesselServiceClient interface {
	FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error)
	Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error)
}

type vesselServiceClient struct {
	c           client.Client
	serviceName string
}

func NewVesselServiceClient(serviceName string, c client.Client) VesselServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.vessel"
	}
	return &vesselServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *vesselServiceClient) FindAvailable(ctx context.Context, in *Specification, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.FindAvailable", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselServiceClient) Create(ctx context.Context, in *Vessel, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.serviceName, "VesselService.Create", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *Specification, *Response) error
	Create(context.Context, *Vessel, *Response) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&VesselService{hdlr}, opts...))
}

type VesselService struct {
	VesselServiceHandler
}

func (h *VesselService) FindAvailable(ctx context.Context, in *Specification, out *Response) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func (h *VesselService) Create(ctx context.Context, in *Vessel, out *Response) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}

func init() { proto.RegisterFile("proto/vessel/vessel.proto", fileDescriptor_vessel_9817d4490e61c20d) }

var fileDescriptor_vessel_9817d4490e61c20d = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x6a, 0xc2, 0x40,
	0x10, 0xc6, 0xd9, 0xa8, 0x31, 0x4e, 0xb1, 0x87, 0xe9, 0x65, 0xb5, 0x15, 0x42, 0x4e, 0x9e, 0x52,
	0x50, 0xfa, 0x00, 0xa5, 0xa5, 0xd0, 0x1e, 0x57, 0x68, 0x8f, 0xb2, 0x6e, 0xa6, 0x76, 0xc1, 0x64,
	0x43, 0x12, 0xa2, 0x7d, 0x8b, 0x3e, 0x42, 0xaf, 0x7d, 0xcb, 0xc2, 0x44, 0x2d, 0x16, 0xd1, 0x53,
	0xe6, 0xcf, 0x37, 0x33, 0x5f, 0x7e, 0x2c, 0x0c, 0xf2, 0xc2, 0x55, 0xee, 0xb6, 0xa6, 0xb2, 0xa4,
	0xd5, 0xf6, 0x13, 0x73, 0x0d, 0xaf, 0x96, 0x2e, 0x4e, 0xad, 0x29, 0x5c, 0x5c, 0x16, 0x75, 0xdc,
	0xb4, 0xa2, 0x6f, 0x01, 0xfe, 0x2b, 0x87, 0x78, 0x09, 0x9e, 0x4d, 0xa4, 0x08, 0xc5, 0xb8, 0xa7,
	0x3c, 0x9b, 0xe0, 0x10, 0x02, 0xa3, 0x73, 0x6d, 0x6c, 0xf5, 0x29, 0xbd, 0x50, 0x8c, 0x3b, 0x6a,
	0x9f, 0xe3, 0x08, 0x20, 0xd5, 0x9b, 0xf9, 0x9a, 0xec, 0xf2, 0xa3, 0x92, 0x2d, 0xee, 0xf6, 0x52,
	0xbd, 0x79, 0xe3, 0x02, 0x22, 0xb4, 0x33, 0x9d, 0x92, 0x6c, 0xf3, 0x32, 0x8e, 0xf1, 0x06, 0x7a,
	0xba, 0xd6, 0x76, 0xa5, 0x17, 0x2b, 0x92, 0x9d, 0x50, 0x8c, 0x03, 0xf5, 0x57, 0xc0, 0x01, 0x04,
	0x6e, 0x9d, 0x51, 0x31, 0xb7, 0x89, 0xf4, 0x79, 0xaa, 0xcb, 0xf9, 0x73, 0x12, 0xbd, 0x40, 0x7f,
	0x96, 0x93, 0xb1, 0xef, 0xd6, 0xe8, 0xca, 0xba, 0xec, 0xc0, 0x98, 0x38, 0x69, 0xcc, 0xfb, 0x67,
	0x2c, 0xfa, 0x12, 0x10, 0x28, 0x2a, 0x73, 0x97, 0x95, 0x84, 0x53, 0xf0, 0x1b, 0x0a, 0xbc, 0xe5,
	0x62, 0x72, 0x1d, 0x1f, 0x21, 0x14, 0x37, 0x74, 0xd4, 0x56, 0x8a, 0x77, 0xd0, 0x6d, 0xa2, 0x52,
	0x7a, 0x61, 0xeb, 0xdc, 0xd4, 0x4e, 0x8b, 0x12, 0xba, 0xa6, 0x20, 0x5d, 0x51, 0xc2, 0xb4, 0x02,
	0xb5, 0x4b, 0x27, 0x3f, 0x02, 0xfa, 0x8d, 0x7a, 0x46, 0x45, 0x6d, 0x0d, 0xa1, 0x82, 0xfe, 0x93,
	0xcd, 0x92, 0xfb, 0x3d, 0x9c, 0xe8, 0xe8, 0x89, 0x03, 0x28, 0xc3, 0xd1, 0x51, 0xcd, 0xfe, 0x5f,
	0x1f, 0xc1, 0x7f, 0xe0, 0x83, 0x78, 0xca, 0xef, 0x99, 0x2d, 0x0b, 0x9f, 0x5f, 0xd2, 0xf4, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0xd3, 0x90, 0x52, 0x66, 0x02, 0x00, 0x00,
}
